import {useMemo} from 'react';
import {useTheme} from 'native-base';
import {Dimensions, StyleSheet} from 'react-native';

const dWidth = Dimensions.get('window').width;
const dHeight = Dimensions.get('window').height;

const deviceWidth = Dimensions.get('window');

const imageHeight = Math.round((deviceWidth.width * 9) / 16);
const imageWidth = deviceWidth.width;

const getGlobalStyles = (props: any) =>
  StyleSheet.create({
    overflowHiddenContainer: {
      flex: 1,
      overflow: 'hidden',
    },
    mainContainer: {
      flex: 1,
      backgroundColor: props.colors.white,
    },
    mainPageContainer: {
      flex: 1,
      backgroundColor: props.colors.lightGrayColor,
    },
    tabBarContainerStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      height: 67,
      paddingBottom: 0,
      backgroundColor: props.colors.white,
      shadowColor: props.colors.black,
      shadowOffset: {
        width: 0,
        height: -3,
      },
      shadowOpacity: 0.08,
      shadowRadius: 4.62,
      elevation: 10,
      borderTopColor: 'transparent',
      borderTopLeftRadius: 15,
      borderTopRightRadius: 15,
    },
    addButtonStyle: {
      marginTop: -70,
      shadowColor: props.colors.primary[500],
      shadowOffset: {
        width: 0,
        height: 8,
      },
      shadowOpacity: 0.25,
      shadowRadius: 4.65,
      elevation: 10,
    },
    walletStyle: {
      backgroundColor: '#F54141',
      height: 55,
      width: 55,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: -70,
      shadowColor: props.colors.primary[500],
      shadowOffset: {
        width: 0,
        height: 8,
      },
      shadowOpacity: 0.25,
      shadowRadius: 4.65,
      elevation: 10,
      borderRadius: 30,
    },
    absoluteFull: {
      position: 'absolute',
      right: 0,
      top: 0,
      bottom: 0,
      left: 0,
    },
    overlayButton: {
      backgroundColor: '#0000004D',
      flex: 1,
    },
    drawerAnimContainer: {
      position: 'absolute',
      top: 0,
      bottom: 0,
      flex: 1,
      width: 290,
    },
    userListHeader: {
      marginBottom: 15,
    },
    codeFiledRoot: {
      marginHorizontal: -5,
      marginBottom: 30,
    },
    markerImageStyle: {
      width: 35,
      height: 40,
    },
    buttonMainStyle: {
      borderColor: 'transparent',
      borderRadius: 8,
      height: 42,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 15,
    },
    opacity5: {
      opacity: 0.5,
    },
    moreContentContainer: {
      backgroundColor: props.colors.primary[600],
    },
    primaryColorText15Style: {
      color: props.colors.white,
      fontSize: 15,
    },
    whiteColorText15Style: {
      color: 'white',
      fontSize: 15,
    },
    marRight10: {
      marginRight: 10,
    },
    marginLeft10: {
      marginLeft: 10,
    },
    privateContainer: {
      backgroundColor: props.colors.lightGrayColor,
      flex: 1,
      justifyContent: 'center',
      alignContent: 'center',
      padding: 40,
      paddingBottom: 67,
    },
    privateContainerImage: {
      height: 200,
      width: 250,
      marginBottom: 20,
    },
    privateContainerTextTitle: {
      fontSize: 18,
      color: props.colors.black,
      textAlign: 'center',
      fontWeight: 'bold',
      marginBottom: 20,
    },
    privateContainerTextDesc: {
      fontSize: 14,
      color: props.colors.grayColor,
      textAlign: 'center',
      marginBottom: 30,
    },
    privateContainerHelpBtn: {
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 30,
    },
    privateContainerHelpBtnTxt: {
      fontSize: 14,
      color: props.colors.primary[500],
      textAlign: 'center',
    },
    loginPageImage: {
      height: 100,
      width: 100,
      marginBottom: 30,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: -1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },

    headerLogo: {
      height: 39,
      width: 39,
    },
    cameraStyle: {
      height: 350,
      width: 350,
      borderRadius: 10,
      flex: 1,
    },
    cameraPreviewContainerStyle: {
      height: 350,
      width: 350,
      overflow: 'hidden',
      borderRadius: 10,
    },
    cameraOverlayStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      top: 0,
      backgroundColor: 'transparent',
      borderWidth: 10,
      borderRadius: 10,
      height: 350,
      width: '100%',
      borderColor: '#00000050',
    },
    borderTopRightStyle: {
      borderRightWidth: 2,
      borderTopWidth: 2,
      borderColor: 'white',
      position: 'absolute',
      right: -2,
      top: -2,
      height: 25,
      borderTopRightRadius: 10,
      width: 25,
    },
    borderBottomLeftStyle: {
      borderLeftWidth: 2,
      borderBottomWidth: 2,
      borderColor: 'white',
      position: 'absolute',
      left: -2,
      bottom: -2,
      height: 25,
      borderBottomLeftRadius: 10,
      width: 25,
    },
    borderTopLeftStyle: {
      borderLeftWidth: 2,
      borderTopWidth: 2,
      borderColor: 'white',
      position: 'absolute',
      left: -2,
      top: -2,
      height: 25,
      borderTopLeftRadius: 10,
      width: 25,
    },
    borderBottomRightStyle: {
      borderRightWidth: 2,
      borderBottomWidth: 2,
      borderColor: 'white',
      position: 'absolute',
      right: -2,
      bottom: -2,
      height: 25,
      borderBottomRightRadius: 10,
      width: 25,
    },
    selectButtonViewStyle: {
      borderRadius: 20,
      paddingHorizontal: 12,
      marginRight: 10,
      marginVertical: 7,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: props.colors.lightGrayColor,
      // flex: 1,
    },
    cubeSelectButtonStyle: {
      padding: 13,
      paddingHorizontal: 10,
      flexDirection: 'row',
      alignItems: 'center',
      borderRadius: 5,
      borderWidth: 1,
      margin: 5,
      backgroundColor: 'white',
      borderColor: props.colors.white,
      flex: 0,
      minHeight: 50,
    },
    radioSelectButtonStyle: {
      padding: 20,
      paddingHorizontal: 0,
      flexDirection: 'row',
      alignItems: 'center',
      borderBottomWidth: 0.5,
      borderRadius: 0,
      marginRight: 0,
      borderBottomColor: '#D0D0D0',
      backgroundColor: 'white',
      marginVertical: 0,
    },
    textBlack3: {
      flex: 1,
      fontSize: 14,
      color: 'black',
    },
    textWhitefl1: {
      fontSize: 14,
      color: 'white',
      flex: 1,
    },
    flexGrowStyle: {
      flexGrow: 1,
    },
    width50percent: {
      width: '50%',
    },
    marginRight5: {
      marginRight: 5,
    },
    marginRight10: {
      marginRight: 10,
    },
    selectCheckStyle: {
      position: 'absolute',
      right: -2,
      bottom: -2,
      width: 14,
      height: 14,
      borderRadius: 7,
      borderWidth: 2,
      borderColor: 'white',
      backgroundColor: props.colors.primary[500],
    },
    allCenter: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    flex1AllCenter: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    tabIconContainer: {
      height: 25,
      // width: 25,
      alignItems: 'center',
      justifyContent: 'center',
      // marginBottom: 5,
    },
    scrollBodyContainer: {
      flexGrow: 1,
      alignItems: 'center',
      justifyContent: 'center',
      padding: 15,
    },
    with100Percent: {
      width: '100%',
    },
    selectTagContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 10,
    },
    selectTagTextContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      top: 0,
    },
    selectTagText: {
      color: props.colors.whiteDark,
      fontSize: 14,
      fontWeight: 'bold',
      textAlign: 'center',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 1.2,
      },
      shadowOpacity: 0.9,
      shadowRadius: 2,
      elevation: 5,
    },
    selectTagIcon: {
      position: 'absolute',
      right: 0,
      bottom: -5,
      borderWidth: 2,
      borderColor: props.colors.lightGrayColor,
      borderRadius: 15,
      backgroundColor: props.colors.lightGrayColor,
    },
    titleTextLg: {
      fontSize: 24,
      lineHeight: 30,
      color: props.colors.black,
      fontWeight: 'bold',
    },
    descTextLg: {
      fontSize: 16,
      color: props.colors.grayColor,
      marginTop: 10,
    },
    footerButtonRowContainer: {
      flexDirection: 'row',
      padding: 15,
      backgroundColor: props.colors.white,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: -1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    footerButtonContainer: {
      padding: 15,
      backgroundColor: props.colors.white,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: -1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    footerButtonContainerNoPad: {
      backgroundColor: props.colors.white,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: -1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    padding15: {
      padding: 15,
    },
    padding20: {
      padding: 20,
    },
    headerShadow: {
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    headerContainer: {
      minHeight: 52,
      maxHeight: 52,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 5,
      width: '100%',
    },
    headerHomeContainer: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      marginLeft: 10,
    },
    headerHomeTitle: {
      fontSize: 18,
      color: 'white',
      fontWeight: 'bold',
      marginLeft: 15,
    },
    headerTitle: {
      flex: 1,
      position: 'absolute',
      left: 0,
      right: 0,
      zIndex: 0,
      paddingHorizontal: 54,
      justifyContent: 'center',
      alignItems: 'center',
    },
    headerTitleText: {
      color: props.colors.black,
      fontWeight: 'bold',
      fontSize: 17,
    },
    statusBadge: {
      position: 'absolute',
      right: -6,
      bottom: -6,
      height: 12,
      width: 12,
      borderWidth: 2,
      borderRadius: 10,
      borderColor: props.colors.primaryDarkChange,
      backgroundColor: props.colors.success[500],
      zIndex: 2,
    },
    flexRowCenter: {
      flexDirection: 'row',
      alignItems: 'center',
      position: 'absolute',
      right: 5,
    },
    flex1RowCenter: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    flexRow: {
      flexDirection: 'row',
    },
    flex1Row: {
      flexDirection: 'row',
      flex: 1,
    },
    homeHeaderBack: {
      backgroundColor: props.colors.lightGrayColor,
    },
    authContainer: {
      flex: 1,
      flexGrow: 1,
      padding: 20,
      paddingTop: 0,
      justifyContent: 'center',
    },
    authContainerText: {
      fontSize: 14,
      color: props.colors.grayColor,
    },
    authPageTitle: {
      fontSize: 20,
      color: props.colors.black,
      fontWeight: 'bold',
      marginBottom: 30,
      textAlign: 'center',
    },
    authPageTitleInfo: {
      fontSize: 20,
      color: props.colors.black,
      fontWeight: 'bold',
      marginBottom: 15,
      textAlign: 'center',
    },
    authPageDescInfo: {
      fontSize: 15,
      color: props.colors.grayColor,
      marginBottom: 30,
      textAlign: 'center',
    },
    authFooterContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 20,
    },
    authFooterVerContainer: {
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 20,
    },
    authFooterText: {
      fontSize: 16,
      color: props.colors.black,
      marginRight: 5,
    },
    confirmText: {
      color: props.colors.primary[500],
      fontWeight: 'bold',
    },
    pinContainer: {
      flex: 1,
      borderWidth: 1,
      borderRadius: 8,
      backgroundColor: props.colors.whiteSecond,
      marginHorizontal: 5,
    },
    pinText: {
      flex: 1,
      height: 61,
      lineHeight: 59,
      textAlign: 'center',
      fontSize: 18,
      fontWeight: 'bold',
      color: props.colors.black,
    },
    splashContainer: {
      // padding: 30,
      // paddingVertical: 50,
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: props.colors.lightGrayColor,
    },
    splashText: {
      fontSize: 22,
      textAlign: 'center',
      fontWeight: 'bold',
      color: props.colors.black,
      marginBottom: 10,
    },
    splashDesc: {
      fontSize: 14,
      textAlign: 'center',
      color: props.colors.grayColor,
    },
    splashPageImage: {
      height: 160,
      width: 160,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      // elevation: 5,
    },
    tabMainContainers: {
      flex: 1,
      marginBottom: 52,
      backgroundColor: props.colors.lightGrayColor,
    },

    tabMainColorContainers: {
      flex: 1,
      marginBottom: 52,
      backgroundColor: props.colors.primary[500],
    },
    tabMainContentContainer: {
      flexGrow: 1,
      paddingBottom: 15,
    },
    tabMainColorContentContainer: {
      flexGrow: 1,
      paddingBottom: 15,
      backgroundColor: props.colors.lightGrayColor,
    },
    tabHostContentContainer: {
      flexGrow: 1,
      paddingBottom: 45,
    },
    edgeSearch: {
      height: 100,
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
      backgroundColor: props.colors.primaryDarkChange,
    },
    edge: {
      height: 40,
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
      backgroundColor: props.colors.primaryDarkChange,
    },
    searchIconContainer: {
      paddingHorizontal: 13,
      alignItems: 'center',
      justifyContent: 'center',
    },
    category: {
      height: 40,
      borderRadius: 20,
      paddingHorizontal: 15,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
      backgroundColor: props.colors.white,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    categorySelected: {
      backgroundColor: props.colors.success[500],
      shadowColor: props.colors.success[500],
    },
    categoryText: {
      fontSize: 14,
      color: props.colors.black,
    },
    categoryTextSelected: {
      color: props.colors.whiteDark,
    },
    titleContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 15,
      marginBottom: 10,
    },
    title: {
      fontSize: 18,
      color: props.colors.black,
      fontWeight: 'bold',
    },
    eventHorizontalContainer: {
      flexDirection: 'row',
      paddingHorizontal: 15,
    },
    eventVerticalContainer: {
      paddingHorizontal: 15,
    },
    eventScroll: {
      overflow: 'visible',
      paddingBottom: 20,
    },
    eventImageItemContainer: {
      backgroundColor: props.colors.borderColor,
      height: 130,
      width: '100%',
      borderTopLeftRadius: 8,
      borderTopRightRadius: 8,
    },
    eventImageHorizontalItemContainer: {
      backgroundColor: props.colors.borderColor,
      width: 110,
      maxWidth: 110,
      borderTopLeftRadius: 8,
      borderBottomLeftRadius: 8,
      flex: 1,
    },
    eventInfoItemContainer: {
      padding: 10,
    },
    eventItemTimeText: {
      fontSize: 13,
      color: props.colors.primary[500],
      marginBottom: 7,
    },
    eventItemTimeTextAds: {
      fontSize: 13,
      color: props.colors.whiteDark,
      marginBottom: 7,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 1.2,
      },
      shadowOpacity: 0.9,
      shadowRadius: 2,
      elevation: 5,
    },
    eventItemTitleText: {
      fontSize: 16,
      color: props.colors.black,
      fontWeight: 'bold',
      marginBottom: 7,
    },
    eventItemTitleTextAds: {
      fontSize: 24,
      color: props.colors.whiteDark,
      fontWeight: 'bold',
      marginBottom: 7,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 1.2,
      },
      shadowOpacity: 0.9,
      shadowRadius: 2,
      elevation: 5,
    },
    eventItemInfoText: {
      fontSize: 13,
      color: props.colors.grayColor,
      flex: 1,
    },
    eventItemInfoTextAds: {
      fontSize: 13,
      color: props.colors.whiteDark,
      flex: 1,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 1.2,
      },
      shadowOpacity: 0.9,
      shadowRadius: 2,
      elevation: 5,
    },
    eventItemInfoIconContainer: {
      width: 14,
      marginRight: 6,
      alignItems: 'center',
      justifyContent: 'center',
    },
    eventItemInfoContainer: {
      flexDirection: 'row',
      marginBottom: 7,
    },
    eventLikeContainer: {
      height: 36,
      width: 36,
      backgroundColor: props.colors.white,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      flex: 1,
    },
    eventLikeHorizontalContainer: {
      height: 36,
      width: 36,
      alignItems: 'center',
      justifyContent: 'center',
      flex: 1,
    },
    eventItemVerticalImage: {
      height: 130,
      width: '100%',
      borderTopLeftRadius: 8,
      borderTopRightRadius: 8,
      resizeMode: 'cover',
    },
    eventItemHorizontalImage: {
      flex: 1,
      borderTopLeftRadius: 8,
      borderBottomLeftRadius: 8,
      resizeMode: 'cover',
    },
    eventHorizontalItemContainer: {
      flex: 1,
      padding: 10,
    },
    eventHorizontalCompanyContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 10,
      paddingVertical: 7,
      borderBottomLeftRadius: 8,
      borderBottomRightRadius: 8,
      backgroundColor: props.colors.lightGrayColor,
    },
    eventHorizontalCompanyImage: {
      height: 24,
      width: 24,
      borderRadius: 12,
      marginRight: 5,
      resizeMode: 'cover',
    },
    eventHorizontalCompanyText: {
      fontSize: 12,
      color: props.colors.black,
    },
    eventLock: {
      position: 'absolute',
      left: 10,
      top: 10,
      width: 36,
      height: 36,
      borderRadius: 8,
      backgroundColor: props.colors.primary[500],
      alignItems: 'center',
      justifyContent: 'center',
    },
    eventAdsContainer: {
      height: 300,
    },
    eventAdsInfoContainer: {
      padding: 20,
      justifyContent: 'flex-end',
      flex: 1,
      overflow: 'hidden',
      borderRadius: 8,
    },
    eventAdsVideo: {
      position: 'absolute',
      top: 0,
      left: 0,
      bottom: 0,
      right: 0,
      borderRadius: 8,
    },
    paddingTop20: {
      paddingTop: 20,
    },
    skeletonVertical: {
      width: 210,
      marginRight: 15,
    },
    categoryContainer: {
      flexDirection: 'row',
      padding: 15,
    },
    animatedContainer: {
      height: '100%',
      flex: 1,
    },
    animatedRowContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      minHeight: 52,
      maxHeight: 52,
      paddingHorizontal: 5,
      width: '100%',
    },
    animatedBox: {
      height: 40,
      zIndex: 1,
    },
    animatedHeaderTitle: {
      flex: 1,
      position: 'absolute',
      left: 0,
      right: 0,
      zIndex: 0,
      // paddingHorizontal: 139,
      paddingHorizontal: 60,
      justifyContent: 'center',
      alignItems: 'center',
    },
    animatedHeaderTitleEvent: {
      paddingRight: 139,
    },
    animatedHeaderTitleText: {
      color: 'black',
      fontWeight: 'bold',
      fontSize: 17,
    },
    eventDetailContainer: {
      backgroundColor: props.colors.lightGrayColor,
      paddingBottom: 72,
    },
    eventDetailImageContainer: {
      backgroundColor: props.colors.borderColor,
      height: 250,
      width: '100%',
    },
    eventDetailInfoContainer: {
      backgroundColor: props.colors.white,
      padding: 15,
      borderRadius: 20,
      marginTop: -20,
      marginBottom: 20,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    eventDetailTagScroll: {
      overflow: 'visible',
      paddingBottom: 10,
    },
    eventDetailTag: {
      borderRadius: 8,
      paddingHorizontal: 9,
      paddingVertical: 3,
      alignSelf: 'flex-start',
      backgroundColor: props.colors.primary[100],
      marginRight: 10,
    },
    eventDetailTagText: {
      fontSize: 13,
      color: props.colors.primary[500],
    },
    eventDetailTitle: {
      fontSize: 22,
      color: props.colors.black,
      fontWeight: 'bold',
      lineHeight: 28,
      marginBottom: 20,
    },
    eventDetailLocInfoContainer: {
      flexDirection: 'row',
      marginBottom: 15,
    },
    eventDetailLocInfo: {
      height: 41,
      width: 41,
      borderRadius: 8,
      backgroundColor: props.colors.primary[100],
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 15,
    },
    eventDetailLocInfoTitle: {
      fontSize: 14,
      color: props.colors.black,
      fontWeight: 'bold',
      marginBottom: 2,
    },
    eventDetailLocInfoDesc: {
      fontSize: 13,
      color: props.colors.grayColor,
    },
    eventDetailActionContainer: {
      flexDirection: 'row',
      marginVertical: 15,
      flex: 1,
    },
    eventDetailInfoTitle: {
      fontSize: 18,
      color: props.colors.black,
      fontWeight: 'bold',
      marginBottom: 10,
    },
    eventDetailInfoImage: {
      width: imageWidth - 30,
      height: imageHeight,
      borderRadius: 8,
      flex: 1,
      marginBottom: 15,
    },
    eventDetailVideoContainer: {
      width: '100%',
      height: 150,
      overflow: 'hidden',
      borderRadius: 8,
      backgroundColor: props.colors.lightGrayColor,
    },
    eventDetailLevelContainer: {
      paddingHorizontal: 15,
      marginBottom: 20,
    },
    eventDetailLevelScrollContainer: {
      paddingHorizontal: 15,
    },
    eventDetailLevelScroll: {
      paddingBottom: 20,
      overflow: 'visible',
    },
    eventStatusCard: {
      flex: 1,
      borderRadius: 8,
      padding: 15,
      paddingHorizontal: 4,
      backgroundColor: props.colors.white,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    eventStatusCircle: {
      minWidth: 42,
      height: 42,
      borderRadius: 21,
      paddingHorizontal: 10,
      backgroundColor: props.colors.primary[100],
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 10,
    },
    eventStatusCircleText: {
      fontSize: 24,
      lineHeight: 34,
      fontWeight: 'bold',
      color: props.colors.primary[500],
      textAlign: 'center',
    },
    eventStatusText: {
      fontSize: 14,
      textAlign: 'center',
      color: props.colors.black,
    },
    eventProgramCircleContainer: {
      marginTop: -15,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
    },
    eventProgramCircle: {
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: props.colors.primary[500],
      borderWidth: 4,
      borderColor: props.colors.white,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    eventProgramLine: {
      width: 2,
      flex: 1,
    },
    eventProgramCard: {
      flex: 1,
      borderRadius: 8,
      backgroundColor: props.colors.white,
      padding: 10,
      marginBottom: 15,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    eventProgramText: {
      fontSize: 13,
      marginBottom: 4,
    },
    eventProgramDateText: {
      fontSize: 13,
      color: props.colors.primary[500],
      marginBottom: 4,
    },
    participantCard: {
      flex: 1,
      width: 132,
      borderRadius: 8,
      padding: 10,
      backgroundColor: props.colors.white,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 15,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    participantAvatarContainer: {
      height: 112,
      width: '100%',
      borderRadius: 60,
      backgroundColor: props.colors.borderColor,
      marginBottom: 10,
    },
    participantAvatar: {
      height: 112,
      width: '100%',
      borderRadius: 60,
    },
    participantName: {
      fontSize: 14,
      color: props.colors.black,
      fontWeight: 'bold',
      textAlign: 'center',
      marginBottom: 2,
    },
    participantDesc: {
      fontSize: 12,
      color: props.colors.grayColor,
      textAlign: 'center',
    },
    commentCard: {
      borderRadius: 8,
      padding: 10,
      backgroundColor: props.colors.white,
      flexDirection: 'row',
      marginBottom: 15,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    commentAvatarContainer: {
      height: 59,
      width: 59,
      borderRadius: 30,
      backgroundColor: props.colors.borderColor,
      marginRight: 10,
    },
    commentAvatar: {
      height: 59,
      width: 59,
      borderRadius: 30,
      backgroundColor: props.colors.borderColor,
    },
    commentTime: {
      fontSize: 12,
      color: props.colors.grayColor,
    },
    commentText: {
      fontSize: 14,
      color: props.colors.black,
    },
    flex1RowSpace: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      flex: 1,
    },
    flex1RowCenterSpace: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      flex: 1,
    },
    commentRateTag: {
      paddingVertical: 1,
      paddingHorizontal: 7,
      borderRadius: 20,
      backgroundColor: props.colors.success[500],
      alignItems: 'center',
      justifyContent: 'center',
      maxHeight: 25,
      flexDirection: 'row',
    },
    commentRateText: {
      fontSize: 14,
      color: props.colors.whiteDark,
      marginLeft: 3,
    },
    commentNameText: {
      fontSize: 14,
      color: props.colors.black,
      fontWeight: 'bold',
      marginBottom: 4,
      flex: 1,
    },
    eventDetailTitleContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 10,
    },
    commentNameContainer: {
      flexDirection: 'row',
      flex: 1,
      justifyContent: 'space-between',
      marginBottom: 5,
    },
    bottomModalContainer: {
      backgroundColor: props.colors.lightGrayColor,
      borderTopRightRadius: 20,
      borderTopLeftRadius: 20,
      borderBottomRightRadius: 0,
      borderBottomLeftRadius: 0,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: -1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    bottomModalHeader: {
      padding: 15,
      backgroundColor: props.colors.white,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    bottomModalTitle: {
      fontSize: 18,
      color: props.colors.black,
      fontWeight: 'bold',
      textAlign: 'center',
    },
    bottomModalBody: {
      flexGrow: 1,
      padding: 15,
    },
    ticketInfoTitle: {
      fontSize: 18,
      color: props.colors.black,
      fontWeight: 'bold',
      marginBottom: 10,
    },
    ticketCard: {
      flexDirection: 'row',
      borderRadius: 8,
      marginBottom: 15,
      backgroundColor: props.colors.white,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    ticketInfo: {
      padding: 10,
      flex: 1,
      flexDirection: 'row',
    },
    ticketImage: {
      height: 65,
      width: 65,
      borderRadius: 8,
      backgroundColor: props.colors.borderColor,
      resizeMode: 'cover',
      marginRight: 10,
    },
    ticketTitle: {
      fontSize: 14,
      color: props.colors.black,
      fontWeight: 'bold',
      marginBottom: 5,
    },
    ticketDate: {
      fontSize: 12,
      color: props.colors.grayColor,
      marginBottom: 5,
    },
    ticketPrice: {
      fontSize: 16,
      color: props.colors.primary[500],
      fontWeight: 'bold',
    },
    ticketRemaining: {
      fontSize: 10,
      color: props.colors.primary[500],
      fontWeight: '300',
    },
    ticketBasketContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      borderTopRightRadius: 8,
      borderBottomRightRadius: 8,
      backgroundColor: props.colors.success[500],
      padding: 10,
      paddingHorizontal: 5,
      width: 76,
    },
    ticketBasketText: {
      fontSize: 14,
      color: props.colors.whiteDark,
      fontWeight: 'bold',
      textAlign: 'center',
    },
    ticketCircleTop: {
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: props.colors.lightGrayColor,
      position: 'absolute',
      top: -9,
      left: -9,
    },
    ticketCircleBottom: {
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: props.colors.lightGrayColor,
      position: 'absolute',
      bottom: -9,
      left: -9,
    },
    basketFooter: {
      marginHorizontal: -15,
      paddingTop: 5,
    },
    basketTotalText: {
      fontSize: 20,
      color: props.colors.black,
      fontWeight: 'bold',
    },
    basketProiceText: {
      fontSize: 20,
      color: props.colors.black,
      fontWeight: 'bold',
      textAlign: 'right',
    },
    basketCard: {
      flexDirection: 'row',
      borderRadius: 8,
      marginBottom: 15,
      backgroundColor: props.colors.white,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    basketInfo: {
      padding: 10,
      flex: 1,
      flexDirection: 'row',
    },
    basketImage: {
      height: 80,
      width: 80,
      borderRadius: 8,
      backgroundColor: props.colors.borderColor,
      resizeMode: 'cover',
      marginRight: 10,
    },
    basketTitle: {
      fontSize: 14,
      color: props.colors.black,
      fontWeight: 'bold',
      marginBottom: 5,
    },
    basketType: {
      fontSize: 14,
      color: props.colors.primary[500],
      fontWeight: 'bold',
      marginBottom: 5,
    },
    basketDate: {
      fontSize: 12,
      color: props.colors.grayColor,
      marginBottom: 5,
    },
    basketPrice: {
      fontSize: 16,
      color: props.colors.black,
      fontWeight: 'bold',
    },
    basketContainer: {
      alignItems: 'center',
      borderTopRightRadius: 8,
      borderBottomRightRadius: 8,
      backgroundColor: props.colors.success[500],
      padding: 5,
      width: 60,
    },
    basketCircleTop: {
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: props.colors.lightGrayColor,
      position: 'absolute',
      top: -9,
      left: -9,
    },
    basketCircleBottom: {
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: props.colors.lightGrayColor,
      position: 'absolute',
      bottom: -9,
      left: -9,
    },
    basketActionContainer: {
      backgroundColor: props.colors.lightGrayColorDark,
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderBottomLeftRadius: 8,
    },
    basketNumberText: {
      fontSize: 20,
      color: props.colors.whiteDark,
      fontWeight: 'bold',
      textAlign: 'center',
    },
    paymentCard: {
      padding: 10,
      flexDirection: 'row',
      alignItems: 'center',
      borderRadius: 8,
      marginBottom: 15,
      backgroundColor: props.colors.white,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    paymentCardSelected: {
      backgroundColor: props.colors.success[500],
      shadowColor: props.colors.success[500],
    },
    paymentLogo: {
      height: 32,
      width: 32,
      borderRadius: 8,
      resizeMode: 'contain',
      marginHorizontal: 10,
      backgroundColor: props.colors.lightGrayColor,
      alignItems: 'center',
      justifyContent: 'center',
    },
    paymentTitle: {
      fontSize: 16,
      fontWeight: 'bold',
    },
    paymentDesc: {
      fontSize: 12,
      color: props.colors.grayColor,
      marginTop: 3,
    },
    paymentCheck: {
      height: 20,
      width: 20,
      borderRadius: 20,
      borderWidth: 2,
      alignItems: 'center',
      justifyContent: 'center',
    },
    paymentModalTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      textAlign: 'center',
      marginBottom: 20,
      color: props.colors.black,
    },
    paymentPriceCard: {
      flexDirection: 'row',
      backgroundColor: props.colors.white,
      padding: 15,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: props.colors.primary[500],
      marginBottom: 20,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    paymentTotalText: {
      fontSize: 16,
      color: props.colors.grayColor,
      marginBottom: 5,
    },
    paymentPriceText: {
      fontSize: 24,
      color: props.colors.black,
      fontWeight: 'bold',
    },
    paymentEventImage: {
      height: 57,
      width: 57,
      borderRadius: 8,
      backgroundColor: props.colors.lightGrayColor,
      resizeMode: 'cover',
    },
    paymentInfoContainer: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      marginBottom: 20,
    },
    paymentInfoTitle: {
      fontSize: 16,
      color: props.colors.grayColor,
      marginBottom: 4,
    },
    paymentInfoText: {
      fontSize: 18,
      color: props.colors.black,
      fontWeight: 'bold',
    },
    paymentAccountCard: {
      backgroundColor: props.colors.white,
      padding: 15,
      borderRadius: 8,
      marginBottom: 20,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
      paddingBottom: 0,
    },
    paymentInfoCard: {
      backgroundColor: props.colors.white,
      borderWidth: 1,
      borderColor: props.colors.warning[500],
      borderStyle: 'dashed',
      padding: 15,
      borderRadius: 8,
      marginBottom: 20,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    paymentModalBody: {
      width: '100%',
      backgroundColor: props.colors.lightGrayColor,
      paddingVertical: 20,
      padding: 15,
      borderRadius: 8,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    paymentInfoDescText: {
      fontSize: 14,
      color: props.colors.black,
    },
    paymentWaitingContainer: {
      backgroundColor: props.colors.white,
      padding: 10,
      borderRadius: 8,
      marginBottom: 15,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    paymentDetailContainer: {
      backgroundColor: props.colors.white,
      padding: 10,
      marginBottom: 15,
      elevation: 5,
    },
    paymentWaitingImageContainer: {
      backgroundColor: props.colors.borderColor,
      width: 100,
      height: 100,
      maxWidth: 100,
      borderRadius: 8,
      flex: 1,
    },
    paymentWaitingImage: {
      flex: 1,
      borderRadius: 8,
      resizeMode: 'cover',
    },
    paymentWaitingEventItemContainer: {
      flexDirection: 'row',
      marginBottom: 10,
    },
    paymentWaitingTicketContainer: {
      padding: 10,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: props.colors.borderColor,
      marginBottom: 10,
    },
    paymentWaitingPriceContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 10,
    },
    paymentWaitingTotal: {
      fontSize: 16,
      color: props.colors.black,
      fontWeight: 'bold',
    },
    paymentWaitingText: {
      fontSize: 16,
      color: props.colors.black,
      fontWeight: 'bold',
      textAlign: 'right',
    },
    ticketNumberText: {
      color: props.colors.black,
    },
    categoryTab: {
      height: 40,
      borderRadius: 20,
      paddingHorizontal: 15,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
      backgroundColor: props.colors.white,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    categoryTabSelected: {
      backgroundColor: props.colors.primary[500],
    },
    categoryTabContainer: {
      flexDirection: 'row',
      padding: 15,
      paddingBottom: 5,
      // position: 'absolute',
      // left: 0,
      // right: 0,
    },
    hostDetailCard: {
      padding: 15,
      backgroundColor: props.colors.white,
      borderRadius: 8,
      marginTop: 120,
      marginBottom: 20,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    hostDetailImageContainer: {
      width: 85,
      height: 85,
      borderRadius: 8,
      marginTop: -57,
      backgroundColor: props.colors.borderColor,
      alignSelf: 'center',
      marginBottom: 15,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    hostDetailImage: {
      width: 85,
      height: 85,
      borderRadius: 8,
      borderWidth: 4,
      borderColor: props.colors.white,
    },
    hostDetailText: {
      color: props.colors.black,
      fontWeight: 'bold',
      textAlign: 'center',
      fontSize: 18,
      marginBottom: 15,
    },
    hostStatusTag: {
      fontSize: 13,
      fontWeight: 'bold',
      textAlign: 'center',
      color: props.colors.primary[500],
      borderWidth: 1,
      borderColor: props.colors.primary[500],
      alignSelf: 'center',
      paddingHorizontal: 9,
      paddingVertical: 2,
      borderRadius: 8,
      marginBottom: 15,
    },
    hostDetailTitle: {
      fontSize: 18,
      color: props.colors.black,
      fontWeight: 'bold',
      marginBottom: 10,
    },
    animatedHeader: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      zIndex: 1,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    rateCard: {
      marginBottom: 15,
      padding: 15,
      backgroundColor: props.colors.white,
      borderRadius: 8,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    rateFormInfoText: {
      fontSize: 12,
      color: props.colors.grayColor,
      alignSelf: 'flex-end',
      marginTop: 2,
    },
    rateFormInfoTextBold: {
      color: props.colors.black,
      fontWeight: 'bold',
    },
    modalBody: {
      width: '100%',
      backgroundColor: props.colors.lightGrayColor,
      padding: 15,
      borderRadius: 8,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    rateTextContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 15,
    },
    rateText: {
      fontSize: 18,
      color: props.colors.black,
      fontWeight: 'bold',
      textAlign: 'center',
      marginBottom: 10,
    },
    notificationListTitle: {
      fontSize: 14,
      color: props.colors.grayColor,
      fontWeight: 'bold',
      marginBottom: 10,
    },
    notificationCard: {
      flexDirection: 'row',
      padding: 10,
      borderRadius: 8,
      backgroundColor: props.colors.white,
      marginBottom: 15,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    notificationTitle: {
      marginTop: 5,
      fontSize: 14,
      fontWeight: 'bold',
      marginBottom: 5,
      color: props.colors.black,
    },
    notificationDesc: {
      fontSize: 13,
      color: props.colors.grayColor,
    },
    notificationIconContainer: {
      height: 50,
      width: 50,
      borderRadius: 25,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
      backgroundColor: props.colors.borderColor,
    },
    notificationIconSuccess: {
      backgroundColor: props.colors.success[500],
    },
    notificationIconError: {
      backgroundColor: props.colors.primary[500],
    },
    notificationIconNewFeature: {
      backgroundColor: props.colors.warning[500],
    },
    moreUserInfoContainer: {
      padding: 20,
      borderBottomLeftRadius: 25,
      borderBottomRightRadius: 25,
      backgroundColor: props.colors.primaryDarkChange,
      marginBottom: 5,
    },
    moreUserAvatar: {
      backgroundColor: props.colors.primary[600],
      height: 100,
      width: 100,
      borderRadius: 50,
      borderWidth: 2,
      borderColor: props.colors.white,
      marginBottom: 15,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    moreUserName: {
      fontSize: 18,
      fontWeight: 'bold',
      color: props.colors.whiteDark,
      textAlign: 'center',
      marginBottom: 3,
      maxWidth: '70%',
    },
    moreUserPhone: {
      fontSize: 12,
      color: props.colors.whiteDark,
      textAlign: 'center',
    },
    marginBottom15: {
      marginBottom: 15,
    },
    moreChangeButtonText: {
      color: props.colors.whiteDark,
      fontWeight: 'bold',
      fontSize: 14,
      flex: 1,
    },
    moreMenuCard: {
      backgroundColor: props.colors.white,
      borderRadius: 8,
      marginBottom: 15,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    menuContainer: {
      paddingHorizontal: 15,
      paddingVertical: 10,
      flexDirection: 'row',
      alignItems: 'center',
    },
    menuIconContainer: {
      height: 40,
      width: 40,
      borderRadius: 20,
      backgroundColor: props.colors.primary[100],
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    menuText: {
      fontSize: 14,
      color: props.colors.black,
      fontWeight: 'bold',
    },
    menuTitle: {
      fontSize: 16,
      color: props.colors.black,
      fontWeight: 'bold',
      marginBottom: 10,
    },
    moreMenuRoleChangerButton: {
      flex: 1,
      height: 48,
      borderRadius: 25,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 15,
      paddingVertical: 5,
      backgroundColor: props.colors.whiteOpacity,
    },
    footerAbsoluteButtonContainer: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      padding: 15,
      backgroundColor: props.colors.white,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: -1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    menuNotificationBadge: {
      height: 14,
      width: 14,
      borderRadius: 7,
      backgroundColor: props.colors.success[500],
      marginHorizontal: 15,
    },
    myCompanyHorizontalContainer: {
      flexDirection: 'row',
    },
    myCompanyScroll: {
      overflow: 'visible',
      paddingBottom: 20,
    },
    myCompanyTitleContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 15,
    },
    myCompanyTitle: {
      fontSize: 16,
      color: props.colors.black,
      fontWeight: 'bold',
    },
    companyCard: {
      maxWidth: 120,
      width: 120,
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: props.colors.white,
      padding: 10,
      borderRadius: 8,
      marginRight: 15,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    companyListCard: {
      maxWidth: '100%',
      width: '100%',
      marginRight: 0,
    },
    companyCardImage: {
      width: 65,
      height: 65,
      borderRadius: 35,
      backgroundColor: props.colors.borderColor,
      marginBottom: 10,
    },
    companyCardTitle: {
      fontSize: 14,
      color: props.colors.black,
      fontWeight: 'bold',
      textAlign: 'center',
      marginBottom: 5,
    },
    companyCardDesc: {
      fontSize: 12,
      color: props.colors.primary[500],
      textAlign: 'center',
    },
    companyListContainer: {
      flexGrow: 1,
      padding: 7.5,
    },
    companyListItemContainer: {
      width: '50%',
    },
    ticketActionContainer: {
      backgroundColor: props.colors.lightGrayColorDark,
      flexDirection: 'row',
      justifyContent: 'flex-end',
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderBottomLeftRadius: 8,
    },
    tabScrollContainer: {
      maxHeight: 60,
    },
    tabViewContainer: {
      minHeight: '100%',
      marginBottom: -60,
      paddingBottom: 60,
    },
    ticketCardContainer: {
      flex: 1,
      width: '100%',
      backgroundColor: props.colors.white,
      borderRadius: 8,
      marginRight: 15,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    ticketQRContainer: {
      padding: 20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    ticketLineContainer: {
      marginVertical: 18,
      height: 1,
      borderRadius: 1,
      borderWidth: 2,
      borderColor: props.colors.borderColor,
      borderStyle: 'dashed',
      zIndex: 0,
    },
    ticketLineBody: {
      position: 'absolute',
      left: 0,
      bottom: 0,
      width: '100%',
      height: 2,
      backgroundColor: props.colors.white,
      zIndex: 1,
    },
    ticketLeftCircle: {
      position: 'absolute',
      left: -18,
      top: -18,
      height: 36,
      width: 36,
      borderRadius: 18,
      borderRightWidth: 1,
      borderRightColor: props.colors.borderColor,
      backgroundColor: props.colors.lightGrayColor,
      zIndex: 2,
    },
    ticketRightCircle: {
      position: 'absolute',
      right: -18,
      top: -18,
      height: 36,
      width: 36,
      borderRadius: 18,
      borderLeftWidth: 1,
      borderLeftColor: props.colors.borderColor,
      backgroundColor: props.colors.lightGrayColor,
      zIndex: 2,
    },
    ticketCardTitle: {
      fontSize: 20,
      color: props.colors.black,
      fontWeight: 'bold',
      textAlign: 'center',
      marginBottom: 10,
    },
    ticketImageContainer: {
      borderRadius: 8,
      overflow: 'hidden',
      backgroundColor: props.colors.borderColor,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    ticketCardValueTitle: {
      fontSize: 14,
      color: props.colors.grayColor,
      marginBottom: 4,
    },
    ticketCardValue: {
      fontSize: 16,
      color: props.colors.color,
      fontWeight: 'bold',
      marginBottom: 15,
    },
    ticketValueContainer: {
      padding: 20,
    },
    qrImage: {
      height: 200,
      width: 200,
    },
    ticketValueRowContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    ticketListItemContainer: {
      marginBottom: 15,
    },
    searchListContainer: {
      flex: 1,
      padding: 15,
    },
    searchInputContainer: {
      flexDirection: 'row',
      padding: 15,
      paddingBottom: 0,
    },
    searchFilterTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: props.colors.black,
      marginBottom: 10,
    },
    searchFilterTagContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginBottom: 5,
    },
    searchFilterTag: {
      flexDirection: 'row',
      borderRadius: 8,
      padding: 10,
      alignItems: 'center',
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    searchFilterTagText: {
      fontSize: 14,
      lineHeight: 18,
    },
    searchFilterCheck: {
      alignItems: 'center',
      justifyContent: 'center',
      height: 20,
      width: 20,
      borderRadius: 10,
      borderWidth: 2,
      marginRight: 10,
    },
    searchLocationButton: {
      flexDirection: 'row',
      backgroundColor: props.colors.white,
      borderRadius: 8,
      padding: 15,
      alignItems: 'center',
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    searchLocationText: {
      flex: 1,
      fontSize: 14,
      color: props.colors.black,
    },
    searchDatePicker: {
      height: 40,
      maxWidth: 'auto',
      backgroundColor: props.colors.white,
      borderWidth: 0,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    searchLocationFilterCard: {
      borderRadius: 8,
      padding: 10,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: props.colors.white,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    searchLocationFilterText: {
      fontSize: 14,
      fontWeight: 'bold',
      lineHeight: 18,
      flex: 1,
    },
    searchLocationFilterDesc: {
      fontSize: 12,
      lineHeight: 18,
      flex: 1,
    },
    appIntroSliderContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      padding: 25,
      paddingVertical: dHeight <= 700 ? 35 : 45,
    },
    appIntroSliderDot: {
      height: 8,
      width: 8,
      borderRadius: 4,
      backgroundColor: props.colors.borderColor,
      marginHorizontal: 4,
    },
    appIntroSliderDotSelected: {
      backgroundColor: props.colors.black,
    },
    appIntroDotContainer: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 0,
    },
    appIntroContainer: {
      flex: 1,
    },
    appIntroImageContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'flex-end',
    },
    appIntroTextContainer: {
      minHeight: 150,
      paddingTop: 35,
      paddingBottom: 0,
      padding: 20,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      marginTop: -20,
      alignItems: 'center',
      backgroundColor: props.colors.white,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: -1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    appIntroTitle: {
      fontSize: 22,
      color: props.colors.black,
      fontWeight: 'bold',
      textAlign: 'center',
      marginBottom: 15,
    },
    appIntroDesc: {
      fontSize: 15,
      lineHeight: 25,
      color: props.colors.grayColor,
      textAlign: 'center',
    },
    appIntroImage: {
      height: '90%',
      width: dWidth - (dHeight <= 700 ? 50 : 10),
      resizeMode: 'contain',
    },
    pageLoadingContainer: {
      position: 'absolute',
      top: 0,
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: props.colors.primaryDarkChange,
      alignItems: 'center',
      justifyContent: 'center',
    },
    pageLoadingTitle: {
      fontSize: 16,
      color: props.colors.whiteDark,
      fontWeight: 'bold',
      textAlign: 'center',
    },
    pageLoadingCircle: {
      alignItems: 'center',
      justifyContent: 'center',
      height: 60,
      width: 60,
      borderRadius: 30,
      backgroundColor: props.colors.whiteDark,
      marginBottom: 20,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    noDataContainer: {
      padding: 15,
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    noDataImage: {
      height: 116,
      width: 180,
      resizeMode: 'cover',
      marginBottom: 7,
    },
    noDataText: {
      fontSize: 14,
      color: props.colors.grayColor,
      textAlign: 'center',
    },
    noDataImageLarge: {
      height: 236,
      width: 300,
      marginBottom: 10,
    },
    noDataTextLarge: {
      fontSize: 16,
    },
    loadingContainer: {
      height: 50,
      padding: 10,
    },
    searchScrollContainer: {
      maxHeight: 70,
    },
    walletContainer: {
      flex: 1,
      paddingBottom: 90,
      backgroundColor: props.colors.lightGrayColor,
    },
    pointContainer: {
      flex: 1,
      backgroundColor: props.colors.lightGrayColor,
    },
    paddingHorizontal15: {
      paddingHorizontal: 15,
    },

    walletEdgeSearch: {
      height: 242,
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
      backgroundColor: props.colors.primaryDarkChange,
    },
    walletHeaderContainer: {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'flex-start',
      paddingLeft: 20,
      paddingRight: 15,
      paddingTop: 40,
      marginBottom: 20,
    },
    walletQrContainer: {
      padding: 12,
      backgroundColor: props.colors.white,
      borderRadius: 15,
      marginRight: 20,
    },
    walletPointText: {
      fontSize: 16,
      color: props.colors.white,
      fontWeight: '700',
    },
    walletPointContainer: {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 10,
    },
    walletPointTextContainer: {
      paddingVertical: 7,
      paddingHorizontal: 20,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.15)',
      borderRadius: 68,
      marginRight: 10,
    },
    walletiTextContainer: {
      backgroundColor: 'rgba(255, 255, 255, 0.15)',
      borderRadius: 68,
      width: 28,
      height: 28,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    walletiText: {
      color: props.colors.white,
    },
    walletTextStyle: {
      fontSize: 12,
      color: '#FEE8E8',
    },
    walletSeparatorStyle: {
      height: '100%',
      width: 1,
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
      marginHorizontal: 20,
    },
    walletCircle: {
      width: 16,
      height: 16,
      backgroundColor: props.colors.white,
      borderRadius: 50,
      marginLeft: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
    flexRowCircle: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    walletPointTextBig: {
      fontSize: 24,
      lineHeight: 28,
    },
    marginBottom10: {
      marginBottom: 10,
    },
    marginBottom20: {
      marginBottom: 20,
    },
    walletButtonContainer: {
      paddingHorizontal: 15,
      flexDirection: 'row',
    },
    walletButton: {
      alignItems: 'center',
      backgroundColor: props.colors.white,
      paddingVertical: 15,
      paddingHorizontal: 5,
      flex: 1,
      borderRadius: 8,
    },
    walletIconContainer: {
      width: 41,
      height: 41,
      borderRadius: 50,
      marginBottom: 15,
      backgroundColor: '#FEE8E8',
      alignItems: 'center',
      justifyContent: 'center',
    },
    walletIconText: {
      color: props.colors.black,
      fontSize: 16,
      fontWeight: '700',
      textAlign: 'center',
    },
    transferText: {
      color: props.colors.black,
      fontSize: 18,
      fontWeight: '700',
      marginTop: 20,
      marginBottom: 10,
    },
    width15: {
      width: 15,
      height: '100%',
    },
    spaceBetween: {
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    walletToggleButton: {
      flexDirection: 'row',
      padding: 4,
      backgroundColor: props.colors.white,
      borderRadius: 60,
      shadowColor: 'rgba(173, 175, 187, 0.35)',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.8,
      shadowRadius: 5,
    },
    walletToggleButtonContainer: {
      paddingHorizontal: 7,
      paddingVertical: 2,
      borderRadius: 70,
    },
    walletToggleText: {
      fontSize: 12,
      fontWeight: '700',
      color: '#747688',
    },
    walletItemContainer: {
      paddingVertical: 11,
      paddingLeft: 10,
      paddingRight: 15,
      shadowColor: 'rgba(173, 175, 187, 0.35)',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.8,
      shadowRadius: 5,
      backgroundColor: props.colors.white,
      flexDirection: 'row',
      borderRadius: 8,
      marginBottom: 14,
      alignItems: 'center',
    },
    walletItemIconContainer: {
      width: 50,
      height: 50,
      backgroundColor: '#30C39E',
      borderRadius: 30,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    walletItemDate: {
      fontSize: 11,
      color: '#747688',
    },
    walletItemTitle: {
      fontSize: 14,
      color: '#120D26',
      fontWeight: 'bold',
    },
    walletItemName: {
      fontSize: 11,
      color: '#747688',
      fontWeight: '700',
    },
    walletItemMiddle: {
      marginRight: 12,
      flex: 1,
    },
    walletGreenText: {
      fontSize: 16,
      fontWeight: '700',
      color: '#30C39E',
    },
    pointContainer1: {
      padding: 15,
      backgroundColor: props.colors.white,
      borderRadius: 8,
      shadowColor: 'rgba(173, 175, 187, 0.35)',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.8,
      shadowRadius: 5,
    },
    pointItemTitle: {
      fontSize: 14,
      fontWeight: 'bold',
    },
    walletItemTitleContainer: {
      paddingHorizontal: 10,
      paddingVertical: 3,
      backgroundColor: '#FEE8E8',
      borderRadius: 68,
    },
    constantPointContainer: {
      paddingHorizontal: 15,
      paddingVertical: 10,
      backgroundColor: props.colors.white,
      borderRadius: 20,
      shadowColor: 'rgba(173, 175, 187, 0.35)',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.8,
      shadowRadius: 5,
      marginRight: 10,
    },

    QRcontainer: {
      flex: 1,
      backgroundColor: '#000',
    },
    qrLoadingStyle: {
      borderRadius: 60,
      height: 60,
      width: 60,
      backgroundColor: 'white',
      justifyContent: 'center',
      shadowColor: 'black',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 3,
    },
    borderTopRightStyle1: {
      borderRightWidth: 5,
      borderTopWidth: 5,
      borderColor: props.colors.primary['500'],
      position: 'absolute',
      right: -15,
      top: -15,
      height: 40,
      borderTopRightRadius: 15,
      width: 40,
      zIndex: 2,
    },
    borderBottomLeftStyle1: {
      borderLeftWidth: 5,
      borderBottomWidth: 5,
      borderColor: props.colors.primary['500'],
      position: 'absolute',
      left: -15,
      bottom: -15,
      height: 40,
      borderBottomLeftRadius: 15,
      width: 40,
      zIndex: 1,
    },
    borderTopLeftStyle1: {
      borderLeftWidth: 5,
      borderTopWidth: 5,
      borderColor: props.colors.primary['500'],
      position: 'absolute',
      left: -15,
      top: -15,
      height: 40,
      borderTopLeftRadius: 15,
      width: 40,
      zIndex: 2,
    },
    borderBottomRightStyle1: {
      borderRightWidth: 5,
      borderBottomWidth: 5,
      borderColor: props.colors.primary['500'],
      position: 'absolute',
      right: -15,
      bottom: -15,
      height: 40,
      borderBottomRightRadius: 15,
      width: 40,
      zIndex: 2,
    },
    rectangleContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'transparent',
    },
    rectangle: {
      height: 250,
      width: 250,
      backgroundColor: 'transparent',
      alignItems: 'center',
      zIndex: 3,
    },
    rectangleSuccess: {
      backgroundColor: 'rgba(0,0,0,0.6)',
      justifyContent: 'center',
    },
    topOverlay: {
      flex: 1,
      height: dWidth,
      width: dWidth,
      backgroundColor: 'rgba(0,0,0,0.6)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    topBottomOverlay: {
      flex: 1,
      height: dWidth,
      width: dWidth,
      backgroundColor: 'rgba(0,0,0,0.6)',
      zIndex: 0,
      alignItems: 'center',
      justifyContent: 'center',
    },
    leftAndRightOverlay: {
      height: '100%',
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.6)',
    },
    rectangleRowContainer: {
      flexDirection: 'row',
      zIndex: 1,
    },
    headerContainer1: {
      position: 'absolute',
      right: 0,
      left: 0,
      top: 0,
    },
    closeButton: {
      height: 40,
      width: 40,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#fff',
      margin: 10,
      borderRadius: 20,
    },
    scanInfoText: {
      position: 'absolute',
      top: -140,
      fontSize: 20,
      textAlign: 'center',
      fontWeight: 'bold',
      color: '#fff',
    },
    scanSuccessText: {
      fontSize: 20,
      textAlign: 'center',
      fontWeight: 'bold',
      color: '#fff',
      marginBottom: 15,
    },
    scanSuccessIcon: {
      height: 115,
      width: 115,
      borderRadius: 70,
      backgroundColor: 'yellow',
      borderWidth: 4,
      borderColor: '#fff',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 20,
      shadowColor: 'black',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 3,
    },
    animationLineStyle: {
      height: 2,
      backgroundColor: '#fff',
      width: '100%',
      shadowColor: props.colors.primary['500'],
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowOpacity: 1,
      shadowRadius: 3,
    },
    pointFlatContainer: {
      width: dWidth / 3,
      paddingVertical: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    pointFlatText: {
      fontWeight: '700',
      fontSize: 24,
      color: props.colors.black,
      lineHeight: 32,
    },
    pointFlatFooterStyle: {
      backgroundColor: props.colors.primary['500'],
      borderRadius: 8,
      height: 42,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 15,
    },
    pointFlatContent: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: props.colors.white,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      shadowColor: 'rgba(173, 175, 187, 0.35)',
      shadowOffset: {
        width: 0,
        height: -1,
      },
      shadowOpacity: 1,
      shadowRadius: 3,
    },
    paddingX9: {
      paddingVertical: 9,
    },
    walletQrContainer2: {
      padding: 12,
      backgroundColor: props.colors.white,
      borderRadius: 15,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      alignItems: 'center',
      justifyContent: 'center',
      marginVertical: 20,
    },
    paymentModalBody2: {
      width: '100%',
      backgroundColor: props.colors.lightGrayColor,
      paddingHorizontal: 38,
      paddingVertical: 23,
      borderRadius: 8,
      shadowColor: props.colors.shadowColor,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 5,
    },
    walletQrXContainer: {
      position: 'absolute',
      right: 15,
      top: 20,
      width: 34,
      height: 34,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 60,
      borderWidth: 1,
      borderColor: '#DEDEDE',
    },
  });

function useGlobalStyles() {
  const {colors} = useTheme();

  const styles = useMemo(() => getGlobalStyles({colors}), [colors]);

  return styles;
}

export default useGlobalStyles;
